services:
  api:
    build:
      context: .
      dockerfile: code/deployment/api/Dockerfile
    container_name: wine_quality_api
    ports:
      - "8000:8000"
    networks:
      - wine_network

  app:
    build:
      context: .
      dockerfile: code/deployment/app/Dockerfile
    container_name: wine_quality_app
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - wine_network

networks:
  wine_network:
